## For this assignment, you need to use Automobile Dataset.  This Automobile Dataset has a different characteristic of an auto such as body-style, wheel-base, engine-type, price, mileage, horsepower, and many more.

### 1. From the given data set, print the first and last five rows.

In [4]:
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

data = pd.read_csv('D:\Dataset\Automobile_data.csv')
print("\n:: First 5 lines ::")
display(data.head())
print("\n:: Last 5 lines ::")
display(data.tail())

:: First 5 lines ::

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

:: Last 5 lines ::

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

### 2. Clean data and update the CSV file.

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

<u>Observations</u>:
* **normalized-losses** seems to numeric but is stored as object type. On eye-rolling I can see '?', which might have caused this.
* Similar case is with **price**, **horsepower**, **peak-rpm**, **bore**
* For **num-of-cylinders**, **num-of-doors** these are indeed a numeric terms but represented as literal string, we can replace it with numbers.

In [3]:
from sklearn.impute import SimpleImputer

simp_imp = SimpleImputer(strategy='median')

def impute_missing_values(column):
    column = column.replace('?', np.nan).astype(np.float64)
    return simp_imp.fit_transform(column.values.reshape(-1,1))

In [4]:
column_with_missin_vals = ["normalized-losses", "price", "horsepower", "peak-rpm", "bore", "stroke"]

for i in column_with_missin_vals:
    data[i] = impute_missing_values(data[i])

In [5]:
data['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [6]:
alpha_numbers = ['two','three','four','five','six','eight','twelve']
data['num-of-cylinders'] = data['num-of-cylinders'].replace(alpha_numbers, [2,3,4,5,6,8,12])

In [7]:
data['num-of-doors'].unique()

array(['two', 'four', '?'], dtype=object)

In [8]:
data['num-of-doors'] = data['num-of-doors'].replace(['two', 'four', '?'], [2, 4, np.nan])
data['num-of-doors'] = impute_missing_values(data['num-of-doors'])

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    float64
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    float64
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    int64
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    float64
 19  stroke             205 non-null    float64
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    float64
 22  peak-rpm           205 non-null    float64
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    float64
dtypes: float64(12), int64(6), object(8)
memory usage: 41.8+ KB

In [10]:
data.to_csv('automobile_cleaned.csv')

### 3. Find the most expensive car company name.

In [11]:
data.sort_values(by=["price"], ascending=False).iloc[0]["make"]

'mercedes-benz'

### 4. Print All Toyota Cars details.

In [12]:
data[data['make']=='toyota']

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
150,1,87.0,toyota,gas,std,2.0,hatchback,fwd,front,95.7,158.7,63.6,54.5,1985,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,35,39,5348.0
151,1,87.0,toyota,gas,std,2.0,hatchback,fwd,front,95.7,158.7,63.6,54.5,2040,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6338.0
152,1,74.0,toyota,gas,std,4.0,hatchback,fwd,front,95.7,158.7,63.6,54.5,2015,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,38,6488.0
153,0,77.0,toyota,gas,std,4.0,wagon,fwd,front,95.7,169.7,63.6,59.1,2280,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,31,37,6918.0
154,0,81.0,toyota,gas,std,4.0,wagon,4wd,front,95.7,169.7,63.6,59.1,2290,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,7898.0
155,0,91.0,toyota,gas,std,4.0,wagon,4wd,front,95.7,169.7,63.6,59.1,3110,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,27,32,8778.0
156,0,91.0,toyota,gas,std,4.0,sedan,fwd,front,95.7,166.3,64.4,53.0,2081,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,6938.0
157,0,91.0,toyota,gas,std,4.0,hatchback,fwd,front,95.7,166.3,64.4,52.8,2109,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,30,37,7198.0
158,0,91.0,toyota,diesel,std,4.0,sedan,fwd,front,95.7,166.3,64.4,53.0,2275,ohc,4,110,idi,3.27,3.35,22.5,56.0,4500.0,34,36,7898.0
159,0,91.0,toyota,diesel,std,4.0,hatchback,fwd,front,95.7,166.3,64.4,52.8,2275,ohc,4,110,idi,3.27,3.35,22.5,56.0,4500.0,38,47,7788.0
160,0,91.0,toyota,gas,std,4.0,sedan,fwd,front,95.7,166.3,64.4,53.0,2094,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,38,47,7738.0
161,0,91.0,toyota,gas,std,4.0,hatchback,fwd,front,95.7,166.3,64.4,52.8,2122,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,8358.0
162,0,91.0,toyota,gas,std,4.0,sedan,fwd,front,95.7,166.3,64.4,52.8,2140,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,28,34,9258.0
163,1,168.0,toyota,gas,std,2.0,sedan,rwd,front,94.5,168.7,64.0,52.6,2169,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8058.0
164,1,168.0,toyota,gas,std,2.0,hatchback,rwd,front,94.5,168.7,64.0,52.6,2204,ohc,4,98,2bbl,3.19,3.03,9.0,70.0,4800.0,29,34,8238.0
165,1,168.0,toyota,gas,std,2.0,sedan,rwd,front,94.5,168.7,64.0,52.6,2265,dohc,4,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9298.0
166,1,168.0,toyota,gas,std,2.0,hatchback,rwd,front,94.5,168.7,64.0,52.6,2300,dohc,4,98,mpfi,3.24,3.08,9.4,112.0,6600.0,26,29,9538.0
167,2,134.0,toyota,gas,std,2.0,hardtop,rwd,front,98.4,176.2,65.6,52.0,2540,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,8449.0
168,2,134.0,toyota,gas,std,2.0,hardtop,rwd,front,98.4,176.2,65.6,52.0,2536,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9639.0
169,2,134.0,toyota,gas,std,2.0,hatchback,rwd,front,98.4,176.2,65.6,52.0,2551,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,9989.0
170,2,134.0,toyota,gas,std,2.0,hardtop,rwd,front,98.4,176.2,65.6,52.0,2679,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11199.0
171,2,134.0,toyota,gas,std,2.0,hatchback,rwd,front,98.4,176.2,65.6,52.0,2714,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,11549.0
172,2,134.0,toyota,gas,std,2.0,convertible,rwd,front,98.4,176.2,65.6,53.0,2975,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669.0
173,-1,65.0,toyota,gas,std,4.0,sedan,fwd,front,102.4,175.6,66.5,54.9,2326,ohc,4,122,mpfi,3.31,3.54,8.7,92.0,4200.0,29,34,8948.0
174,-1,65.0,toyota,diesel,turbo,4.0,sedan,fwd,front,102.4,175.6,66.5,54.9,2480,ohc,4,110,idi,3.27,3.35,22.5,73.0,4500.0,30,33,10698.0
175,-1,65.0,toyota,gas,std,4.0,hatchback,fwd,front,102.4,175.6,66.5,53.9,2414,ohc,4,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,9988.0
176,-1,65.0,toyota,gas,std,4.0,sedan,fwd,front,102.4,175.6,66.5,54.9,2414,ohc,4,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,10898.0
177,-1,65.0,toyota,gas,std,4.0,hatchback,fwd,front,102.4,175.6,66.5,53.9,2458,ohc,4,122,mpfi,3.31,3.54,8.7,92.0,4200.0,27,32,11248.0
178,3,197.0,toyota,gas,std,2.0,hatchback,rwd,front,102.9,183.5,67.7,52.0,2976,dohc,6,171,mpfi,3.27,3.35,9.3,161.0,5200.0,20,24,16558.0
179,3,197.0,toyota,gas,std,2.0,hatchback,rwd,front,102.9,183.5,67.7,52.0,3016,dohc,6,171,mpfi,3.27,3.35,9.3,161.0,5200.0,19,24,15998.0
180,-1,90.0,toyota,gas,std,4.0,sedan,rwd,front,104.5,187.8,66.5,54.1,3131,dohc,6,171,mpfi,3.27,3.35,9.2,156.0,5200.0,20,24,15690.0
181,-1,115.0,toyota,gas,std,4.0,wagon,rwd,front,104.5,187.8,66.5,54.1,3151,dohc,6,161,mpfi,3.27,3.35,9.2,156.0,5200.0,19,24,15750.0

### 5. Count total cars per company.

In [13]:
data['make'].value_counts()

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
subaru           12
volkswagen       12
volvo            11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           5
isuzu             4
alfa-romero       3
jaguar            3
chevrolet         3
renault           2
mercury           1
Name: make, dtype: int64

### 6. Find each company’s Highest price car.

In [14]:
data.sort_values('price', ascending=False).groupby(['make']).first()

,symboling,normalized-losses,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
make,,,,,,,,,,,,,,,,,,,,,,,,,
alfa-romero,3,115.0,gas,std,2.0,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,4,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
audi,1,158.0,gas,turbo,4.0,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,5,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0
bmw,0,115.0,gas,std,2.0,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,6,209,mpfi,3.62,3.39,8.0,182.0,5400.0,16,22,41315.0
chevrolet,0,81.0,gas,std,4.0,sedan,fwd,front,94.5,158.8,63.6,52.0,1909,ohc,4,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,6575.0
dodge,3,145.0,gas,turbo,2.0,hatchback,fwd,front,95.9,173.2,66.3,50.2,2811,ohc,4,156,mfi,3.60,3.90,7.0,145.0,5000.0,19,24,12964.0
honda,0,85.0,gas,std,4.0,sedan,fwd,front,96.5,175.4,65.2,54.1,2465,ohc,4,110,mpfi,3.15,3.58,9.0,101.0,5800.0,24,28,12945.0
isuzu,2,115.0,gas,std,2.0,hatchback,rwd,front,96.0,172.6,65.2,51.4,2734,ohc,4,119,spfi,3.43,3.23,9.2,90.0,5000.0,24,29,11048.0
jaguar,0,115.0,gas,std,2.0,sedan,rwd,front,102.0,191.7,70.6,47.8,3950,ohcv,12,326,mpfi,3.54,2.76,11.5,262.0,5000.0,13,17,36000.0
mazda,0,115.0,diesel,std,4.0,sedan,rwd,front,104.9,175.0,66.1,54.4,2700,ohc,4,134,idi,3.43,3.64,22.0,72.0,4200.0,31,39,18344.0
mercedes-benz,1,115.0,gas,std,2.0,hardtop,rwd,front,112.0,199.2,72.0,55.4,3715,ohcv,8,304,mpfi,3.80,3.35,8.0,184.0,4500.0,14,16,45400.0
mercury,1,115.0,gas,turbo,2.0,hatchback,rwd,front,102.7,178.4,68.0,54.8,2910,ohc,4,140,mpfi,3.78,3.12,8.0,175.0,5000.0,19,24,16503.0
mitsubishi,3,115.0,gas,turbo,2.0,hatchback,fwd,front,95.9,173.2,66.3,50.2,2921,ohc,4,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,14869.0
nissan,3,194.0,gas,turbo,2.0,hatchback,rwd,front,91.3,170.7,67.9,49.7,3139,ohcv,6,181,mpfi,3.43,3.27,7.8,200.0,5200.0,17,23,19699.0
peugot,0,161.0,gas,turbo,4.0,sedan,rwd,front,108.0,186.7,68.3,56.0,3130,l,4,134,mpfi,3.61,3.21,7.0,142.0,5600.0,18,24,18150.0
plymouth,3,115.0,gas,turbo,2.0,hatchback,rwd,front,95.9,173.2,66.3,50.2,2818,ohc,4,156,spdi,3.59,3.86,7.0,145.0,5000.0,19,24,12764.0
porsche,3,115.0,gas,std,2.0,convertible,rwd,rear,89.5,168.9,65.0,51.6,2800,ohcf,6,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,37028.0
renault,2,115.0,gas,std,2.0,hatchback,fwd,front,96.1,176.8,66.6,50.5,2460,ohc,4,132,mpfi,3.46,3.90,8.7,95.0,5200.0,23,31,9895.0
saab,2,104.0,gas,turbo,4.0,sedan,fwd,front,99.1,186.6,66.5,56.1,2847,dohc,4,121,mpfi,3.54,3.07,9.0,160.0,5500.0,19,26,18620.0
subaru,0,85.0,gas,turbo,4.0,wagon,4wd,front,96.9,173.6,65.4,54.9,2650,ohcf,4,108,mpfi,3.62,2.64,7.7,111.0,4800.0,23,23,11694.0
toyota,2,134.0,gas,std,2.0,convertible,rwd,front,98.4,176.2,65.6,53.0,2975,ohc,4,146,mpfi,3.62,3.50,9.3,116.0,4800.0,24,30,17669.0
volkswagen,0,115.0,diesel,turbo,4.0,sedan,fwd,front,100.4,180.2,66.9,55.1,2579,ohc,4,97,idi,3.01,3.40,23.0,68.0,4500.0,33,38,13845.0
volvo,-1,95.0,gas,turbo,4.0,sedan,rwd,front,109.1,188.8,68.9,55.5,3062,ohc,4,141,mpfi,3.78,3.15,9.5,114.0,5400.0,19,25,22625.0

### 7. Find the average mileage of each car making company.

In [15]:
data.groupby(['make'])[['city-mpg', 'highway-mpg']].mean()

                city-mpg  highway-mpg
make
alfa-romero    20.333333    26.666667
audi           18.857143    24.142857
bmw            19.375000    25.375000
chevrolet      41.000000    46.333333
dodge          28.000000    34.111111
honda          30.384615    35.461538
isuzu          31.000000    36.000000
jaguar         14.333333    18.333333
mazda          25.705882    31.941176
mercedes-benz  18.500000    21.000000
mercury        19.000000    24.000000
mitsubishi     24.923077    31.153846
nissan         27.000000    32.944444
peugot         22.454545    26.636364
plymouth       28.142857    34.142857
porsche        17.400000    26.000000
renault        23.000000    31.000000
saab           20.333333    27.333333
subaru         26.333333    30.750000
toyota         27.500000    32.906250
volkswagen     28.583333    34.916667
volvo          21.181818    25.818182

### 8. Sort all cars by Price column.

In [16]:
data.sort_values(by=['price'])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
138,2,83.0,subaru,gas,std,2.0,hatchback,fwd,front,93.7,156.9,63.4,53.7,2050,ohcf,4,97,2bbl,3.62,2.36,9.0,69.0,4900.0,31,36,5118.0
18,2,121.0,chevrolet,gas,std,2.0,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,3,61,2bbl,2.91,3.03,9.5,48.0,5100.0,47,53,5151.0
50,1,104.0,mazda,gas,std,2.0,hatchback,fwd,front,93.1,159.1,64.2,54.1,1890,ohc,4,91,2bbl,3.03,3.15,9.0,68.0,5000.0,30,31,5195.0
150,1,87.0,toyota,gas,std,2.0,hatchback,fwd,front,95.7,158.7,63.6,54.5,1985,ohc,4,92,2bbl,3.05,3.03,9.0,62.0,4800.0,35,39,5348.0
76,2,161.0,mitsubishi,gas,std,2.0,hatchback,fwd,front,93.7,157.3,64.4,50.8,1918,ohc,4,92,2bbl,2.97,3.23,9.4,68.0,5500.0,37,41,5389.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17,0,115.0,bmw,gas,std,4.0,sedan,rwd,front,110.0,197.0,70.9,56.3,3505,ohc,6,209,mpfi,3.62,3.39,8.0,182.0,5400.0,15,20,36880.0
128,3,115.0,porsche,gas,std,2.0,convertible,rwd,rear,89.5,168.9,65.0,51.6,2800,ohcf,6,194,mpfi,3.74,2.90,9.5,207.0,5900.0,17,25,37028.0
73,0,115.0,mercedes-benz,gas,std,4.0,sedan,rwd,front,120.9,208.1,71.7,56.7,3900,ohcv,8,308,mpfi,3.80,3.35,8.0,184.0,4500.0,14,16,40960.0
16,0,115.0,bmw,gas,std,2.0,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,6,209,mpfi,3.62,3.39,8.0,182.0,5400.0,16,22,41315.0
74,1,115.0,mercedes-benz,gas,std,2.0,hardtop,rwd,front,112.0,199.2,72.0,55.4,3715,ohcv,8,304,mpfi,3.80,3.35,8.0,184.0,4500.0,14,16,45400.0

### 9. Concatenate two data frames using the following conditions. Create two data frames using the following two Dicts, Concatenate those two data frames and create a key for each data frame.

```
germanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'],
              'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '],
                'Price' : [29995, 23600, 61500 , 58900]}
```

In [17]:
germanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'],
              'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '],
                'Price' : [29995, 23600, 61500 , 58900]}

dfg = pd.DataFrame(germanCars)
dfj = pd.DataFrame(japaneseCars)
dfgj = pd.concat([dfg,dfj], ignore_index=True)

In [18]:
display(dfg)
display(dfj)
display(dfgj)

    Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

       Company  Price
0       Toyota  29995
1        Honda  23600
2       Nissan  61500
3  Mitsubishi   58900

       Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

### 10. Merge two data frames using the following condition. Create two data frames using the following two Dicts, Merge two data frames, and append the second data frame as a new column to the first data frame.

```
car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'],
             'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'],
                  'horsepower': [141, 80, 182 , 160]}
```

In [19]:
car_Price = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'],
             'Price': [23845, 17995, 135925 , 71400]}
car_Horsepower = {'Company': ['Toyota', 'Honda', 'BMV', 'Audi'],
                  'horsepower': [141, 80, 182 , 160]}

df_car_price = pd.DataFrame(car_Price)
df_horsepower = pd.DataFrame(car_Horsepower)
df_merged = pd.merge(df_car_price, df_horsepower, how ='inner', on ='Company')

In [20]:
display(df_car_price)
display(df_horsepower)
display(df_merged)

  Company   Price
0  Toyota   23845
1   Honda   17995
2     BMV  135925
3    Audi   71400

  Company  horsepower
0  Toyota         141
1   Honda          80
2     BMV         182
3    Audi         160

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160